from github import Auth
from github import Github

import argparse

from dotenv import load_dotenv
import json
from loguru import logger
import os



load_dotenv()
ACCESS_TOKEN = os.getenv("GITHUB_TOKEN")

def create_github_issues(issues_list, repo_name, progress_callback=None):
    """
    Creates GitHub issues from a list of issue dictionaries.
    
    Args:
        issues_list (list): List of dicts with title, description, priority, type
        repo_name (str): The repository name (owner/repo)
        progress_callback (callable, optional): function that accepts a float (0.0 to 1.0) for progress
        
    Returns:
        tuple: (success (bool), created_links (list))
    """
    if not ACCESS_TOKEN:
        logger.error("GITHUB_TOKEN not found in environment variables.")
        return False, []

    created_links = []
    try:
        auth = Auth.Token(ACCESS_TOKEN)
        g = Github(auth=auth)
        repo = g.get_repo(repo_name)
        
        total = len(issues_list)
        
        for idx, issue in enumerate(issues_list):
            title = issue.get("title", "No Title")
            description = issue.get("description", "No Description")
            # Enhance body
            body = f"{description}\n\n*This issue was automatically generated by Project Assistant.*"
            if "priority" in issue:
                body += f"\n\n**Priority:** {issue['priority']}"
            if "type" in issue:
                body += f"\n**Type:** {issue['type']}"
                
            new_issue = repo.create_issue(title=title, body=body)
            created_links.append(new_issue.html_url)
            logger.info(f"Created issue: {title}")
            
            if progress_callback:
                progress_callback((idx + 1) / total)
            
        return True, created_links
    except Exception as e:
        logger.error(f"GitHub Error: {e}")
        return False, []

if __name__ == "__main__":
    
    parser = argparse.ArgumentParser(description="Process transcriptions to generate PRD.")
    parser.add_argument("issues_path", type=str, help="Path to the json with the issues.")
    parser.add_argument("--repo", "-r", type=str, help="Repo directory.", default=None)
    auth = Auth.Token(ACCESS_TOKEN)
    logger.info(f"Authenticated to GitHub: {auth}")
    g = Github(auth=auth)
    logger.info(f"1")
    repo = g.get_repo("Adria-Colbai/issue-api")
    logger.info(f"2")
    args = parser.parse_args()
    with open(args.issues_path, "r", encoding="utf-8") as f:
        issues_data = json.load(f)
    
    logger.info(f"Loaded {len(issues_data.get("issues"))} issues from JSON.")
    for issue in issues_data.get("issues", []):
        title = issue.get("title", "No Title")
        description = issue.get("description", "No Description")
        body = f"{description}\n\n*This issue was automatically generated.*"
        logger.info(f"Creating issue: {title}")
        repo.create_issue(title=title, body=body)